import os
import json
from pathlib import Path

ROOT = Path(r"C:/Users/Alexa/Desktop/SandBox")
PROJECTS = ROOT / 'projects'
PLAN_DIR = ROOT / '.hermes' / 'plans'
PLAN_DIR.mkdir(parents=True, exist_ok=True)
REPORT_PATH = PLAN_DIR / 'vscode-audit-report.md'

def detect_stack(repo_path: Path):
    pkg = repo_path / 'package.json'
    req = repo_path / 'requirements.txt'
    manage = repo_path / 'manage.py'
    if pkg.exists():
        try:
            j = json.loads(pkg.read_text(encoding='utf-8'))
        except Exception:
            return 'node'
        deps = ' '.join(list(j.get('dependencies',{}).keys()) + list(j.get('devDependencies',{}).keys())).lower()
        if 'next' in deps or 'nextjs' in deps:
            return 'nextjs'
        if 'bun' in deps or j.get('packageManager','').lower().startswith('bun'):
            return 'bun'
        return 'node'
    if manage.exists() or (req.exists() and 'django' in req.read_text(encoding='utf-8').lower()):
        return 'django'
    if req.exists():
        return 'python'
    return None

expected_files = ['settings.json','launch.json','tasks.json','extensions.json']

lines = []
lines.append('# VS Code Workspace Audit Report')
lines.append('Generated by hermes script: generate_vscode_audit_report.py')
lines.append('')
lines.append('Summary per project under projects/:')
lines.append('')

projects = sorted([p for p in PROJECTS.iterdir() if p.is_dir()])
for p in projects:
    name = p.name
    stack = detect_stack(p)
    vscode = p / '.vscode'
    has_vscode = vscode.exists()
    lines.append(f'## {name}')
    lines.append(f'- Path: {p.as_posix()}')
    lines.append(f'- Detected stack: {stack or "unknown"}')
    lines.append(f'- .vscode present: {"Yes" if has_vscode else "No"}')
    if has_vscode:
        files = {f.name: f for f in vscode.glob('*.json')}
        for ef in expected_files:
            if ef in files:
                ok = True
                err = None
                try:
                    # strict JSON validation for launch/tasks/extensions; settings may be JSON but we parse
                    json.loads(files[ef].read_text(encoding='utf-8'))
                except Exception as e:
                    ok = False
                    err = str(e)
                lines.append(f'  - {ef}: exists — valid: {"Yes" if ok else "No"}{"; error: "+err if err else ""}')
            else:
                lines.append(f'  - {ef}: MISSING')
        # quick next actions
        missing = [ef for ef in expected_files if ef not in files]
        if missing:
            lines.append(f'  - Next actions: create {", ".join(missing)} using {stack} template')
        else:
            lines.append('  - Next actions: none (files present)')
    else:
        lines.append(f'  - Next actions: create .vscode/ with settings.json, launch.json (if applicable), tasks.json, extensions.json using {stack or "node"} template')
    lines.append('')

# Global verification checklist
lines.append('---')
lines.append('## Verification checklist')
lines.append('- [ ] All sub-repos have .vscode/ directory')
lines.append('- [ ] All .vscode/*.json files are valid JSON')
lines.append('- [ ] settings.json has language-specific formatter blocks matching stack')
lines.append('- [ ] launch.json has stack-appropriate debug configurations')
lines.append('- [ ] tasks.json has build/test tasks matching stack')
lines.append('- [ ] extensions.json recommends only relevant extensions')
lines.append('')
lines.append('---')
lines.append('## Suggested customizations (proposed defaults)')
lines.append('- Add Bun launch configs for repos with packageManager=bun or detected bun: Banking, Banking-like repos')
lines.append('- Merge Django + Next.js settings for dual-stack repos: rhixecompany-comics')
lines.append('- Add dev/prod tasks for full-stack repos (ecom, rhixecompany-comics, xamehi)')
lines.append('')
lines.append('---')
lines.append('## Notes')
lines.append('- I did NOT commit any changes. If you want commits, confirm and I will commit per-repo with conventional commit messages (type: description).')
lines.append('- To proceed: (1) confirm customizations to apply, (2) I will patch .vscode files, (3) validate again, (4) commit on your confirmation.')

REPORT_PATH.write_text('\n'.join(lines), encoding='utf-8')
print(f'Wrote report to {REPORT_PATH.as_posix()}')
