# Generated by Django 5.1.9 on 2025-05-31 10:14

import api.libary.models
import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Artist",
                "verbose_name_plural": "Artists",
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=5000, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=5000, verbose_name="Title"),
                ),
                ("updated_at", models.DateField(verbose_name="Updated At")),
                ("link", models.URLField(default="")),
                (
                    "numimages",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Total Images"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapter",
                "verbose_name_plural": "Chapters",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ComicImage",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("link", models.URLField(default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.libary.models.comic_image_location,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "ico",
                                    "jpg",
                                    "svg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "bmp",
                                    "webp",
                                    "tiff",
                                    "ttf",
                                    "eot",
                                    "woff",
                                    "woff2",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("downloaded", "Downloaded"),
                            ("uptodate", "Uptodate"),
                            ("cached", "Cached"),
                        ],
                        max_length=13,
                        null=True,
                    ),
                ),
                ("checksum", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "ComicImage",
                "verbose_name_plural": "ComicImages",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text")),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.CreateModel(
            name="UserComic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "UserComic",
                "verbose_name_plural": "UserComics",
            },
        ),
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Website",
                "verbose_name_plural": "Websites",
            },
        ),
        migrations.CreateModel(
            name="ChapterImage",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("link", models.URLField(default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.libary.models.chapter_image_location,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "ico",
                                    "jpg",
                                    "svg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "bmp",
                                    "webp",
                                    "tiff",
                                    "ttf",
                                    "eot",
                                    "woff",
                                    "woff2",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("downloaded", "Downloaded"),
                            ("uptodate", "Uptodate"),
                            ("cached", "Cached"),
                        ],
                        max_length=13,
                        null=True,
                    ),
                ),
                ("checksum", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapterimages",
                        to="libary.chapter",
                    ),
                ),
            ],
            options={
                "verbose_name": "ChapterImage",
                "verbose_name_plural": "ChapterImages",
            },
        ),
        migrations.CreateModel(
            name="Comic",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=5000, unique=True, verbose_name="Title"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=5000, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("ongoing", "Ongoing"),
                            ("hiatus", "Hiatus"),
                            ("dropped", "Dropped"),
                            ("season end", "Season End"),
                            ("coming soon", "Coming Soon"),
                        ],
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=10, verbose_name="Rating"
                    ),
                ),
                ("updated_at", models.DateField(verbose_name="Updated At")),
                ("link", models.URLField(default="")),
                (
                    "numchapters",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Total Chapters"
                    ),
                ),
                (
                    "numimages",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Total Images"
                    ),
                ),
                (
                    "serialization",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Serialization",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artistcomics",
                        to="libary.artist",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorcomics",
                        to="libary.author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorycomics",
                        to="libary.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comic",
                "verbose_name_plural": "Comics",
                "ordering": ["-updated_at"],
            },
        ),
    ]
