# Generated by Django 5.1.9 on 2025-06-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libary', '0004_alter_comic_artist_alter_comic_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Updated At'),
        ),
    ]
