#!/usr/bin/env python3
"""Generate the enhancement-batch1 report from analysis_slice1.json."""
import json, os

D = json.load(open("C:/Users/Alexa/Desktop/SandBox/analysis_slice1.json"))
ANALYZED = len(D)

def tmpl_dirs(e):
    t = [r[1] for r in e["meta"]["refs"] if r[0] == "template"]
    dirs = sorted(set(x.split("/")[1] for x in t if "/" in x))
    return dirs, t

def suggestion(e):
    m = e["meta"]
    f = e["file"]
    parts = []
    dirs, _ = tmpl_dirs(e)
    if m["refs"]:
        if dirs:
            parts.append(
                f"resolve {len(m['refs'])} dead reference(s) to templates/{dirs[0]}/ "
                f"(dir missing): either create the template files or replace the inline "
                f"'Template References' block with the actual content / point to templates/_shared"
            )
        else:
            parts.append(f"fix {len(m['refs'])} dead template reference(s)")
    if not m["plan"]:
        parts.append("populate empty frontmatter `plan:` with a one-line execution plan or a plan-file path")
    if not m["has_rules"]:
        parts.append("add an explicit `## Rules` section (Do/Don't constraints) or reference templates/_shared/rules-core.md")
    if not m["has_phases"]:
        parts.append("add a `## Phases`/`## Workflow` section with numbered steps")
    if not m["has_acc_or_verify"]:
        parts.append("add a `## Verification`/`## Acceptance Criteria` section")
    return "; ".join(parts)

# Rank: dead refs first (most concrete defect), then total issue value, then size
def rank_key(e):
    m = e["meta"]
    return (-len(m["refs"]), -m["value"], -m["size"])

ranked = sorted(D, key=rank_key)
TOP = ranked[:15]

strong = [e["file"] for e in D if e["meta"]["value"] >= 4]
minor = [e["file"] for e in D if 2 <= e["meta"]["value"] <= 3]
good = [e["file"] for e in D if not e["meta"]["issues"]]

def status_ones(e):
    m = e["meta"]
    if not m["issues"]:
        return "OK"
    return "minor"

lines = []
lines.append("# Prompt Quality Enhancement Analysis — Slice 1")
lines.append("")
lines.append("**Generated by read-only analysis (boost-prompts quality pipeline). No prompt files were modified.**")
lines.append("")
lines.append(f"- **Slice analyzed:** 60 prompt files (the delegation header stated \"70\" but enumerated 60 unique paths; all 60 exist).")
lines.append(f"- **Method:** Python static parse of YAML frontmatter (`yaml.safe_load`) + structural/regex heuristics over the body. Reference targets resolved against the actual `templates/` tree on disk.")
lines.append(f"- **Enhancement criteria applied:** frontmatter richness (description/tags/plan/formatter), instruction clarity & rule-strengthening, redundancy, instruction-ratio, structural completeness (Goal/Context/Workflow/Rules/Verification), and dead-reference detection.")
lines.append("")
lines.append("## Headline findings")
lines.append("")
lines.append("- **`plan` frontmatter is empty in 59/60 files** (only `debugger-prompt.prompt.md` sets it). This is the single most systemic gap.")
lines.append("- **52/60 files contain dead `templates/<name>/` references** — 121 distinct broken links. The referenced per-prompt template directories (e.g. `templates/breakdown-plan/`, `templates/cosmosdb-datamodeling/`) do **not** exist on disk; only `templates/_shared/` and a few others are present. These prompts point to template files that were never created.")
lines.append("- **22/60 lack an explicit workflow/phases section**, **17/60 lack a `## Rules` section**, and **12/60 lack any acceptance/verification criteria**.")
lines.append("- **Frontmatter `description` and `tags` are present in all 60 files**, and `formatter: default` is set in 59/60 — so enrichment effort should concentrate on `plan`, structure, and broken template references rather than metadata basics.")
lines.append("")
lines.append("## TOP 15 highest-value enhancement candidates")
lines.append("")
lines.append("| # | file | primary issue(s) | suggested enhancement (concrete) |")
lines.append("|---|------|------------------|----------------------------------|")
for i, e in enumerate(TOP, 1):
    m = e["meta"]
    dirs, _ = tmpl_dirs(e)
    issue_bits = []
    if m["refs"]:
        issue_bits.append(f"{len(m['refs'])} dead template ref(s)")
    if not m["plan"]:
        issue_bits.append("empty `plan`")
    if not m["has_rules"]:
        issue_bits.append("no Rules section")
    if not m["has_phases"]:
        issue_bits.append("no Phases section")
    if not m["has_acc_or_verify"]:
        issue_bits.append("no Verification/Acceptance")
    issue_str = "; ".join(issue_bits) if issue_bits else "minor"
    lines.append(f"| {i} | `{e['file']}` | {issue_str} | {suggestion(e)} |")
lines.append("")
lines.append("## Remaining files — one-line verdict")
lines.append("")
for e in ranked[15:]:
    m = e["meta"]
    f = e["file"]
    if not m["issues"]:
        v = "OK — already good"
    else:
        # terse verdict
        bits = []
        if m["refs"]:
            bits.append(f"{len(m['refs'])} dead ref(s)")
        if not m["plan"]:
            bits.append("empty plan")
        if not m["has_rules"]:
            bits.append("no Rules")
        if not m["has_phases"]:
            bits.append("no Phases")
        if not m["has_acc_or_verify"]:
            bits.append("no Verify")
        v = "minor — " + "; ".join(bits) if bits else "minor"
    lines.append(f"- `{f}`: {v}")
lines.append("")
lines.append("## Summary counts")
lines.append("")
lines.append(f"- **Total files analyzed:** {ANALYZED}")
lines.append(f"- **Strong candidates (>=4 issue flags):** {len(strong)}")
lines.append(f"- **Minor candidates (2-3 issue flags):** {len(minor)}")
lines.append(f"- **Already-good (no issues):** {len(good)}")
lines.append("")
lines.append("> Note: 59/60 share the empty-`plan` defect and 52/60 share the dead-`templates/` defect, so a single batch remediation (scripted `plan` population + decision to create-or-remove the missing template dirs) would resolve the bulk of findings efficiently.")
lines.append("")
lines.append(f"**Report path:** `C:/Users/Alexa/AppData/Local/hermes/prompts/docs/enhancement-batch1.md`")
lines.append(f"**Counts:** analyzed={ANALYZED}, strong={len(strong)}, minor={len(minor)}, already-good={len(good)}")

out = "\n".join(lines)
os.makedirs("C:/Users/Alexa/AppData/Local/hermes/prompts/docs", exist_ok=True)
with open("C:/Users/Alexa/AppData/Local/hermes/prompts/docs/enhancement-batch1.md", "w", encoding="utf-8") as f:
    f.write(out)
print("written", len(out), "bytes")
