# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'mcp', '~> 0.4.0'

group :development do
  gem 'rake', '~> 13.0'
  gem 'minitest', '~> 5.18'
  gem 'rubocop', '~> 1.50'
  gem 'rubocop-minitest', '~> 0.31'
  gem 'rubocop-rake', '~> 0.6'
end
