#!/bin/bash
# Echo back arguments to test run_skill_script with args

echo "Arguments received: $@"
echo "Number of arguments: $#"

if [ $# -eq 0 ]; then
    echo "No arguments provided."
else
    echo "Arguments breakdown:"
    for i in "$@"; do
        echo "  - $i"
    done
fi
