# Generated by Django 5.0.10 on 2025-01-17 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comic",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comicuser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chapterimage",
            name="comic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="apps.comic"
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="comic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comicchapters",
                to="apps.comic",
            ),
        ),
        migrations.AddField(
            model_name="comicimage",
            name="comic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comicitems",
                to="apps.comic",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chaptercomments",
                to="apps.chapter",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="comic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comiccomments",
                to="apps.comic",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usercomments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comic",
            name="genres",
            field=models.ManyToManyField(blank=True, to="apps.genre"),
        ),
        migrations.AddField(
            model_name="comic",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comictype",
                to="apps.type",
            ),
        ),
        migrations.AddField(
            model_name="useritem",
            name="comic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="apps.comic",
            ),
        ),
        migrations.AddField(
            model_name="useritem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comic",
            name="users",
            field=models.ManyToManyField(
                blank=True, through="apps.UserItem", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
