<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-09-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
=======
# Generated by Django 3.2.13 on 2022-09-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
>>>>>>> 6031d8f (chore: initial local project setup for xamehi.tv)
