import { CalendarX2Icon, TriangleAlertIcon, TruckIcon } from "lucide-react";

import type { Item } from "@/components/shadcn-studio/blocks/datatable-transaction";

/**
 * Default statistics card data for admin dashboard
 * Used as fallback when live stats are not available
 */
export const statisticsCardData = [
  {
    changePercentage: "+18.2%",
    icon: <TruckIcon className="size-4" />,
    title: "Shipped Orders",
    value: "42",
  },
  {
    changePercentage: "-8.7%",
    icon: <TriangleAlertIcon className="size-4" />,
    title: "Damaged Returns",
    value: "8",
  },
  {
    changePercentage: "+4.3%",
    icon: <CalendarX2Icon className="size-4" />,
    title: "Missed Delivery Slots",
    value: "27",
  },
];

/**
 * Earning data for dashboard widgets
 * Contains platform information and earnings data
 */
export const earningData = [
  {
    earnings: "-$23,569.26",
    img: "https://cdn.shadcnstudio.com/ss-assets/blocks/dashboard-application/widgets/zipcar.png",
    platform: "Zipcar",
    progressPercentage: 75,
    technologies: "Vuejs & HTML",
  },
  {
    earnings: "-$12,650.31",
    img: "https://cdn.shadcnstudio.com/ss-assets/blocks/dashboard-application/widgets/bitbank.png",
    platform: "Bitbank",
    progressPercentage: 25,
    technologies: "Figma & React",
  },
];

/**
 * Sample transaction data for admin dashboard
 * Used as fallback when live transaction data is not available
 */
export const transactionData: Item[] = [
  {
    amount: 316.0,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-1.png",
    avatarFallback: "JA",
    email: "jack@shadcnstudio.com",
    id: "1",
    name: "Jack Alfredo",
    paidBy: "mastercard",
    status: "paid",
  },
  {
    amount: 253.4,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-2.png",
    avatarFallback: "MG",
    email: "maria.g@shadcnstudio.com",
    id: "2",
    name: "Maria Gonzalez",
    paidBy: "visa",
    status: "pending",
  },
  {
    amount: 852.0,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-3.png",
    avatarFallback: "JD",
    email: "john.doe@shadcnstudio.com",
    id: "3",
    name: "John Doe",
    paidBy: "mastercard",
    status: "paid",
  },
  {
    amount: 889.0,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-4.png",
    avatarFallback: "EC",
    email: "emily.carter@shadcnstudio.com",
    id: "4",
    name: "Emily Carter",
    paidBy: "visa",
    status: "pending",
  },
  {
    amount: 723.16,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-5.png",
    avatarFallback: "DL",
    email: "david.lee@shadcnstudio.com",
    id: "5",
    name: "David Lee",
    paidBy: "mastercard",
    status: "paid",
  },
  {
    amount: 612.0,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-6.png",
    avatarFallback: "SP",
    email: "sophia.patel@shadcnstudio.com",
    id: "6",
    name: "Sophia Patel",
    paidBy: "mastercard",
    status: "failed",
  },
  {
    amount: 445.25,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-7.png",
    avatarFallback: "RW",
    email: "robert.wilson@shadcnstudio.com",
    id: "7",
    name: "Robert Wilson",
    paidBy: "visa",
    status: "paid",
  },
  {
    amount: 297.8,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-8.png",
    avatarFallback: "LM",
    email: "lisa.martinez@shadcnstudio.com",
    id: "8",
    name: "Lisa Martinez",
    paidBy: "mastercard",
    status: "processing",
  },
  {
    amount: 756.9,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-9.png",
    avatarFallback: "MT",
    email: "michael.thompson@shadcnstudio.com",
    id: "9",
    name: "Michael Thompson",
    paidBy: "visa",
    status: "paid",
  },
  {
    amount: 189.5,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-10.png",
    avatarFallback: "AJ",
    email: "amanda.johnson@shadcnstudio.com",
    id: "10",
    name: "Amanda Johnson",
    paidBy: "mastercard",
    status: "pending",
  },
  {
    amount: 1024.75,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-11.png",
    avatarFallback: "KB",
    email: "kevin.brown@shadcnstudio.com",
    id: "11",
    name: "Kevin Brown",
    paidBy: "visa",
    status: "paid",
  },
  {
    amount: 367.2,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-12.png",
    avatarFallback: "SD",
    email: "sarah.davis@shadcnstudio.com",
    id: "12",
    name: "Sarah Davis",
    paidBy: "mastercard",
    status: "failed",
  },
  {
    amount: 598.45,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-13.png",
    avatarFallback: "CG",
    email: "christopher.garcia@shadcnstudio.com",
    id: "13",
    name: "Christopher Garcia",
    paidBy: "visa",
    status: "processing",
  },
  {
    amount: 821.3,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-14.png",
    avatarFallback: "JR",
    email: "jennifer.rodriguez@shadcnstudio.com",
    id: "14",
    name: "Jennifer Rodriguez",
    paidBy: "mastercard",
    status: "paid",
  },
  {
    amount: 156.75,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-15.png",
    avatarFallback: "DM",
    email: "daniel.miller@shadcnstudio.com",
    id: "15",
    name: "Daniel Miller",
    paidBy: "visa",
    status: "pending",
  },
  {
    amount: 934.1,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-16.png",
    avatarFallback: "NW",
    email: "nicole.white@shadcnstudio.com",
    id: "16",
    name: "Nicole White",
    paidBy: "mastercard",
    status: "paid",
  },
  {
    amount: 412.85,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-17.png",
    avatarFallback: "AL",
    email: "anthony.lopez@shadcnstudio.com",
    id: "17",
    name: "Anthony Lopez",
    paidBy: "visa",
    status: "failed",
  },
  {
    amount: 675.5,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-18.png",
    avatarFallback: "MH",
    email: "michelle.harris@shadcnstudio.com",
    id: "18",
    name: "Michelle Harris",
    paidBy: "mastercard",
    status: "processing",
  },
  {
    amount: 289.95,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-19.png",
    avatarFallback: "JC",
    email: "james.clark@shadcnstudio.com",
    id: "19",
    name: "James Clark",
    paidBy: "visa",
    status: "paid",
  },
  {
    amount: 1156.25,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-20.png",
    avatarFallback: "RL",
    email: "rachel.lewis@shadcnstudio.com",
    id: "20",
    name: "Rachel Lewis",
    paidBy: "mastercard",
    status: "pending",
  },
  {
    amount: 543.6,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-21.png",
    avatarFallback: "TY",
    email: "thomas.young@shadcnstudio.com",
    id: "21",
    name: "Thomas Young",
    paidBy: "visa",
    status: "paid",
  },
  {
    amount: 789.3,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-22.png",
    avatarFallback: "SB",
    email: "stephanie.brown@shadcnstudio.com",
    id: "22",
    name: "Stephanie Brown",
    paidBy: "mastercard",
    status: "processing",
  },
  {
    amount: 425.75,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-23.png",
    avatarFallback: "BM",
    email: "brandon.moore@shadcnstudio.com",
    id: "23",
    name: "Brandon Moore",
    paidBy: "visa",
    status: "failed",
  },
  {
    amount: 1203.5,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-24.png",
    avatarFallback: "KT",
    email: "kelly.taylor@shadcnstudio.com",
    id: "24",
    name: "Kelly Taylor",
    paidBy: "mastercard",
    status: "paid",
  },
  {
    amount: 356.2,
    avatar: "https://cdn.shadcnstudio.com/ss-assets/avatar/avatar-25.png",
    avatarFallback: "MA",
    email: "mark.anderson@shadcnstudio.com",
    id: "25",
    name: "Mark Anderson",
    paidBy: "visa",
    status: "pending",
  },
];
