#!/usr/bin/env python3
"""
profile_config_fix.py — Apply non-destructive pointer files for missing
SOUL.md / USER.md / MEMORY.md / .hermes.md / AGENTS.md / CLAUDE.md / .cursorrules
in Hermes profiles and the repo root.

DRY principle: each created file is a thin pointer to the canonical source
(~/AppData/Local/hermes/SOUL.md, ~/AppData/Local/hermes/memories/USER.md, etc.).
No rules are duplicated — pointers reference single sources of truth.

Usage:
    python scripts/profile_config_fix.py [--dry-run]
"""
from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# === Configuration ===

REPO_ROOT = Path(__file__).resolve().parent.parent
HERMES_HOME = Path.home() / "AppData/Local/hermes"
PROFILES_DIR = HERMES_HOME / "profiles"
MEMORIES_DIR = HERMES_HOME / "memories"

# Canonical sources (single source of truth) — DRY: one source per file
CANONICAL_SOURCES = {
    "SOUL.md": HERMES_HOME / "SOUL.md",
    "USER.md": MEMORIES_DIR / "USER.md",
    "MEMORY.md": MEMORIES_DIR / "MEMORY.md",
    ".hermes.md": REPO_ROOT / ".hermes.md",
    "AGENTS.md": REPO_ROOT / "AGENTS.md",
    "CLAUDE.md": REPO_ROOT / "CLAUDE.md",
    ".cursorrules": REPO_ROOT / ".cursorrules",
}

# Files to manage in each profile (only those the audit tracks)
PROFILE_FILES = ["SOUL.md", "USER.md", "MEMORY.md", ".hermes.md", "AGENTS.md", "CLAUDE.md", ".cursorrules"]

# Repo-root context files (no identity files in repo)
REPO_CONTEXT_FILES = [".hermes.md", "AGENTS.md", "CLAUDE.md", ".cursorrules"]


# === Pointer file templates ===

# Per-file pointer template. The 'kind' controls the body text.
# All files are < 20 lines, all are pointers, no rule duplication.
POINTER_TEMPLATES = {
    "SOUL.md": """# {profile_label} Profile — SOUL.md Pointer

> Canonical source: `{canonical}` (read-only inheritance)

This profile inherits identity, persona, and operating principles from the
canonical SOUL.md in the Hermes home directory.

To view the live source: `cat "{canonical}"`
To override locally: replace this file with profile-specific content.

Generated by `scripts/profile_config_fix.py` at {timestamp}.
""",
    "USER.md": """# {profile_label} Profile — USER.md Pointer

> Canonical source: `{canonical}`

Inherits user identity, environment, preferences, and standing goals from
the canonical USER.md.

To view the live source: `cat "{canonical}"`
To customize for this profile: replace this file with profile-specific content.

Generated by `scripts/profile_config_fix.py` at {timestamp}.
""",
    "MEMORY.md": """# {profile_label} Profile — MEMORY.md Pointer

> Canonical source: `{canonical}`

Inherits durable agent notes, environment facts, tool quirks, and lessons
from the canonical MEMORY.md.

To view the live source: `cat "{canonical}"`
To add profile-specific memory: replace this file with profile-specific content.

Generated by `scripts/profile_config_fix.py` at {timestamp}.
""",
    ".hermes.md": """# {profile_label} — .hermes.md Pointer

> Canonical source: `{canonical}`

Inherits project-level Hermes overrides (profiles, MCP servers, hooks, plugins,
multi-file change protocol) from the workspace-root .hermes.md.

To view the live source: `cat "{canonical}"`
To override locally: replace this file with project-specific overrides.

Generated by `scripts/profile_config_fix.py` at {timestamp}.
""",
    "AGENTS.md": """# {profile_label} — AGENTS.md Pointer

> Canonical source: `{canonical}`

Inherits agent guidance (persona, communication style, execution preferences)
from the workspace-root AGENTS.md.

To view the live source: `cat "{canonical}"`
To customize locally: replace this file with profile-specific guidance.

Generated by `scripts/profile_config_fix.py` at {timestamp}.
""",
    "CLAUDE.md": """# {profile_label} — CLAUDE.md Pointer

> Canonical source: `{canonical}`

Inherits Claude-specific guidance from the workspace-root CLAUDE.md.

To view the live source: `cat "{canonical}"`
To customize locally: replace this file with profile-specific Claude guidance.

Generated by `scripts/profile_config_fix.py` at {timestamp}.
""",
    ".cursorrules": """# {profile_label} — .cursorrules Pointer

> Canonical source: `{canonical}`

Inherits Cursor IDE rules from the workspace-root .cursorrules.

To view the live source: `cat "{canonical}"`
To customize locally: replace this file with profile-specific Cursor rules.

Generated by `scripts/profile_config_fix.py` at {timestamp}.
""",
}


# === Helpers ===

def is_pointer_file(path: Path) -> bool:
    """Detect if a file is already a generated pointer."""
    if not path.exists():
        return False
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
        return "scripts/profile_config_fix.py" in text
    except Exception:
        return False


def canonical_exists(fname: str) -> bool:
    """Check if the canonical source for a file exists."""
    src = CANONICAL_SOURCES.get(fname)
    return src is not None and src.exists()


def render_pointer(fname: str, label: str) -> str:
    """Render a pointer file body."""
    canonical = CANONICAL_SOURCES[fname]
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    template = POINTER_TEMPLATES[fname]
    return template.format(
        profile_label=label,
        canonical=str(canonical),
        timestamp=timestamp,
    )


# === Plan computation ===

def compute_plan() -> dict:
    """Compute the set of files that need to be created.

    Skip:
    - Files that already exist (and are not already pointers that we generated)
    - Files where the canonical source does not exist (cannot create a pointer)
    - Repo-root context files that the audit tracks
    """
    plan = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "repo_root": str(REPO_ROOT),
        "hermes_home": str(HERMES_HOME),
        "actions": [],  # {action, path, fname, reason, dry_run}
        "skipped": [],  # {path, fname, reason}
        "summary": {"would_create": 0, "skipped": 0, "already_exists": 0},
    }

    # Repo root context files
    for fname in REPO_CONTEXT_FILES:
        target = REPO_ROOT / fname
        if target.exists() and not is_pointer_file(target):
            plan["summary"]["already_exists"] += 1
            plan["skipped"].append({"path": str(target), "fname": fname, "reason": "exists_non_pointer"})
            continue
        if target.exists() and is_pointer_file(target):
            plan["summary"]["already_exists"] += 1
            plan["skipped"].append({"path": str(target), "fname": fname, "reason": "exists_pointer"})
            continue
        if not canonical_exists(fname):
            plan["summary"]["skipped"] += 1
            plan["skipped"].append({"path": str(target), "fname": fname, "reason": "canonical_missing"})
            continue
        plan["summary"]["would_create"] += 1
        plan["actions"].append({
            "action": "create",
            "path": str(target),
            "fname": fname,
            "scope": "repo-root",
            "canonical": str(CANONICAL_SOURCES[fname]),
        })

    # Per-profile files
    if PROFILES_DIR.exists():
        for profile_dir in sorted(PROFILES_DIR.iterdir()):
            if not profile_dir.is_dir():
                continue
            profile_name = profile_dir.name
            for fname in PROFILE_FILES:
                target = profile_dir / fname
                if target.exists() and not is_pointer_file(target):
                    plan["summary"]["already_exists"] += 1
                    plan["skipped"].append({"path": str(target), "fname": fname, "reason": "exists_non_pointer"})
                    continue
                if target.exists() and is_pointer_file(target):
                    plan["summary"]["already_exists"] += 1
                    plan["skipped"].append({"path": str(target), "fname": fname, "reason": "exists_pointer"})
                    continue
                if not canonical_exists(fname):
                    plan["summary"]["skipped"] += 1
                    plan["skipped"].append({"path": str(target), "fname": fname, "reason": "canonical_missing"})
                    continue
                plan["summary"]["would_create"] += 1
                plan["actions"].append({
                    "action": "create",
                    "path": str(target),
                    "fname": fname,
                    "scope": f"profile:{profile_name}",
                    "canonical": str(CANONICAL_SOURCES[fname]),
                })

    return plan


# === Apply ===

def apply_plan(plan: dict, dry_run: bool = True) -> dict:
    """Apply the plan, writing pointer files. Returns an execution report."""
    report = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "dry_run": dry_run,
        "created": [],
        "errors": [],
    }

    for action in plan["actions"]:
        target = Path(action["path"])
        scope = action["scope"]
        label = "SandBox" if scope == "repo-root" else f"{scope.replace('profile:', '')}"
        try:
            body = render_pointer(action["fname"], label)
            if not dry_run:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(body, encoding="utf-8")
            report["created"].append({
                "path": str(target),
                "fname": action["fname"],
                "scope": scope,
                "bytes": len(body),
                "sha256_first16": __import__("hashlib").sha256(body.encode()).hexdigest()[:16],
            })
        except Exception as e:
            report["errors"].append({"path": str(target), "error": str(e)})

    return report


# === Main ===

def main():
    dry_run = "--apply" not in sys.argv
    if "--dry-run" in sys.argv:
        dry_run = True

    plan = compute_plan()
    report = apply_plan(plan, dry_run=dry_run)

    # Output
    out_dir = REPO_ROOT / ".hermes" / "plans" / "2026-08-28-five-goals-execution"
    out_dir.mkdir(parents=True, exist_ok=True)
    if dry_run:
        (out_dir / "g1-fix-dry-run.json").write_text(json.dumps({"plan": plan, "report": report}, indent=2), encoding="utf-8")
    else:
        (out_dir / "g1-fix-applied.json").write_text(json.dumps({"plan": plan, "report": report}, indent=2), encoding="utf-8")

    print(f"profile_config_fix.py — {'DRY RUN' if dry_run else 'APPLY'}")
    print(f"  Plan: {plan['summary']['would_create']} files to create")
    print(f"  Skipped: {plan['summary']['skipped']}")
    print(f"  Already exist: {plan['summary']['already_exists']}")
    print(f"  Created: {len(report['created'])}")
    print(f"  Errors: {len(report['errors'])}")
    if report["errors"]:
        for e in report["errors"]:
            print(f"    - {e['path']}: {e['error']}")
    print(f"  Report: {out_dir / ('g1-fix-dry-run.json' if dry_run else 'g1-fix-applied.json')}")
    return 0 if not report["errors"] else 1


if __name__ == "__main__":
    sys.exit(main())
