#!/usr/bin/env python3
"""Apply the top-5 ranked free models to Hermes config.

Reads:
  - .hermes/reports/test-providers-probe-results.json
  - templates/free-model-catalog.md (for context_length, max_output, reasoning)
  - templates/probe-live-template.md (for elapsed_s, exit)

Score formula (matches the prompt's Phase 4):
  score = (1 if knowledge_cutoff is recent) +
          (1 if context_length >= 32000) +
          (1 if reasoning) +
          (1 if max_output >= 4096) +
          (1 if exit == 0)
Max score = 5. Tiebreak by lowest elapsed_s.

Then applies:
  hermes config set model.default <top1.provider>:<top1.model>
  hermes config set model.provider <top1.provider>
  hermes fallback clear
  hermes fallback add <top2.provider>:<top2.model>   (x4)

Run:
    python scripts/apply_config.py [--dry-run] [--ranked-output PATH]
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[5]
RESULTS_JSON = REPO_ROOT / ".hermes/reports/test-providers-probe-results.json"
CATALOG = REPO_ROOT / ".github/prompts/operations/test-providers-models/templates/free-model-catalog.md"
RANKING = REPO_ROOT / ".github/prompts/operations/test-providers-models/templates/ranking-report.md"
HERMES_BIN = "hermes"

RECENT_KC_YEAR = 2025  # year threshold for "recent knowledge cutoff"


def load_catalog_meta() -> dict[str, dict[str, int | bool | None]]:
    """Parse context_length, max_output, reasoning from the catalog (per-model)."""
    out: dict[str, dict[str, int | bool | None]] = {}
    if not CATALOG.exists():
        return out
    for line in CATALOG.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^\|\s*(\d+)\s*\|\s*`?([\w-]+)`?\s*\|\s*`?([^`]+)`?\s*\|[^|]*\|[^|]*\|(\d+|\d{4,})\s*\|(\d+|\d{4,})", line)
        if m:
            idx = int(m.group(1))
            provider = m.group(2)
            model = m.group(3).strip()
            ctx = int(m.group(4)) if m.group(4).isdigit() else 0
            mxo = int(m.group(5)) if m.group(5).isdigit() else 0
            out[f"{provider}:{model}"] = {"context_length": ctx, "max_output": mxo}
    return out


def score(row: dict, catalog_meta: dict[str, dict]) -> dict:
    """Apply the score formula and return an augmented row."""
    kc = row.get("claims", {}).get("knowledge_cutoff")
    kc_recent = False
    if kc and isinstance(kc, str):
        m = re.match(r"^(\d{4})", kc)
        if m:
            kc_recent = int(m.group(1)) >= RECENT_KC_YEAR
    key = f"{row['provider']}:{row['model']}"
    meta = catalog_meta.get(key, {})
    ctx = meta.get("context_length") or 0
    mxo = meta.get("max_output") or 0
    rsn = row.get("claims", {}).get("reasoning")
    reasoning_yes = rsn == "yes"
    exit_ok = row.get("exit") == 0
    s = (1 if kc_recent else 0) + (1 if ctx >= 32000 else 0) + (1 if reasoning_yes else 0) + (1 if mxo >= 4096 else 0) + (1 if exit_ok else 0)
    return {
        "provider": row["provider"],
        "model": row["model"],
        "exit": row.get("exit"),
        "elapsed_s": row.get("elapsed_s"),
        "failure": (row.get("failure") or {}).get("reason") if (row.get("failure") or {}).get("failed") else None,
        "knowledge_cutoff": kc,
        "context_length": ctx,
        "max_output": mxo,
        "reasoning": rsn,
        "score": s,
        "kc_recent": kc_recent,
    }


def render_ranking(ranked: list[dict], applied: list[str] | None) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    body = "| Rank | Score | Provider | Model | Knowledge Cutoff | Context | Reasoning | Max Output | Latency (s) | Exit |\n"
    body += "|------|-------|----------|-------|------------------|---------|-----------|------------|-------------|------|\n"
    for i, r in enumerate(ranked[:10], 1):
        kc = r.get("knowledge_cutoff") or "?"
        ctx = r.get("context_length") or "?"
        rsn = r.get("reasoning") or "?"
        mxo = r.get("max_output") or "?"
        lat = r.get("elapsed_s") or "?"
        exit_code = r.get("exit")
        failure = r.get("failure") or ""
        exit_label = f"{exit_code}{' ('+failure+')' if failure else ''}"
        body += f"| {i} | {r['score']} | `{r['provider']}` | `{r['model']}` | {kc} | {ctx} | {rsn} | {mxo} | {lat} | {exit_label} |\n"
    cfg = ""
    if applied:
        cfg = (
            "\n## Configuration applied\n\n"
            "```bash\n"
            + "\n".join(str(x) for x in applied)
            + "\n```\n"
        )
    return f"""---
name: ranking-report
description: "Final ranking of probed free models by score (0-5), generated by `scripts/apply_config.py` on {now}."
---

# Free-model ranking -- {now}

> Source: `.hermes/reports/test-providers-probe-results.json` scored with the formula
> `score = recent_kc + context_ge_32k + reasoning + max_output_ge_4k + exit_0` (max 5).
> Tiebreak: lowest `elapsed_s`. Top 5 become the primary + fallback chain.

{body}
{cfg}

## Verification

- [ ] `hermes config show | grep -E 'model|fallback'` matches the table above.
- [ ] `hermes config check` exits 0.
- [ ] `hermes chat --provider <top1.provider> --model <top1.model> -q "ping" --oneshot` exits 0.
"""


def hermes(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run([HERMES_BIN, *args], capture_output=True, text=True, timeout=60)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Score + rank only; do not call `hermes config set`")
    parser.add_argument("--ranked-output", type=Path, default=RANKING, help="Where to write the ranking report")
    args = parser.parse_args()

    if not RESULTS_JSON.exists():
        print(f"ERROR: {RESULTS_JSON} not found; run scripts/run_probes.py first")
        return 1
    rows = json.loads(RESULTS_JSON.read_text(encoding="utf-8"))
    catalog_meta = load_catalog_meta()
    ranked = sorted([score(r, catalog_meta) for r in rows],
                   key=lambda r: (-r["score"], r.get("elapsed_s") or 1e9))
    print("Top 10 ranking:")
    for i, r in enumerate(ranked[:10], 1):
        print(f"  {i:2d}. score={r['score']} exit={r['exit']} {r['provider']}:{r['model']}")

    top5 = [r for r in ranked if r["score"] >= 3][:5]
    if len(top5) < 5:
        print(f"WARNING: only {len(top5)} models with score >= 3 found; using top 5 from ranked")
        top5 = ranked[:5]
    applied: list[str] = []
    if args.dry_run:
        print("DRY RUN -- not applying config")
    elif len(top5) >= 1:
        primary = top5[0]
        applied.append(f"hermes config set model.default {primary['provider']}:{primary['model']}")
        applied.append(f"hermes config set model.provider {primary['provider']}")
        print(f"\nApplying: primary = {primary['provider']}:{primary['model']} (score={primary['score']})")
        r = hermes("config", "set", "model.default", f"{primary['provider']}:{primary['model']}")
        print(f"  set model.default -> exit={r.returncode}")
        r = hermes("config", "set", "model.provider", primary['provider'])
        print(f"  set model.provider -> exit={r.returncode}")
        r = hermes("fallback", "clear")
        print(f"  fallback clear -> exit={r.returncode}")
        for fb in top5[1:5]:
            target = f"{fb['provider']}:{fb['model']}"
            r = hermes("fallback", "add", target)
            applied.append(f"hermes fallback add {target}")
            print(f"  fallback add {target} -> exit={r.returncode}")
        # Verify
        print("\nVerification:")
        r = hermes("config", "check")
        print(f"  config check -> exit={r.returncode}")
        r = hermes("config", "show")
        print(f"  config show (last 1500 chars):")
        print("  " + (r.stdout[-1500:] if r.stdout else "").replace("\n", "\n  "))
        r = hermes("fallback", "list")
        print(f"  fallback list (last 800 chars):")
        print("  " + (r.stdout[-800:] if r.stdout else "").replace("\n", "\n  "))

    args.ranked_output.write_text(render_ranking(ranked, applied), encoding="utf-8")
    print(f"\nWROTE: {args.ranked_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
